### ISSUE TITLE
Register existing services when creating containers

### ISSUE THREAD

**Issue by roryprimrose** [introtocomputerscience/azure-function-autofac-dependency-injection#25]
I would like to have existing services that are registered by Azure Functions to be ported over to the created Autofac containers. The IWebJobsStartup implementation exposes 73 services in Microsoft.NET.Sdk.Functions 1.0.19. For example, the one I'm interested in is ILoggerFactory. 

![image](https://user-images.githubusercontent.com/2044291/44990711-3d87b980-afd5-11e8-9fe1-af6726a4cdaf.png)

I port the existing services in an ASP.Net project by referencing the Autofac.Extensions.DependencyInjection package which provides a ```builder.Populate(services)``` method (see https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacRegistration.cs#L50). 

The problem this solves is that the Functions platform already has out of the box registrations that custom code could then build upon. These "existing" services are not currently available via the Autofac containers.

**Comment by rawrspace** [comment]
That sounds like a great idea @roryprimrose . I will try to have a look as soon as I have time and see what I can do. If anyone else stumbles upon this issue and wants to have a go at it I will gladly accept any help.

**Comment by roryprimrose** [comment]
I wrote this around midnight so it was a bit brief. I'll give this crack.

**Comment by roryprimrose** [comment]
Unfortunately this will produce a breaking change. The ```IServiceCollection``` values need to be provided down to the shared project via the ```Microsoft.Extensions.DependencyInjection``` package. That package needs a minimum support of NET461 instead of NET46.

**Comment by roryprimrose** [comment]
Alternatively, you keep NET46 and roll out a feature version and only support this under the netstandard version of the library. There seems little point to this though because if someone is really restricted to NET46 then they could use an older version of this package.

**Comment by roryprimrose** [comment]
I've been looking into this in pockets of spare time today. This is roughly what I have in mind.

Design concepts:
1. Required: There is an issue with providing services to a ContainerBuilder that is owned and managed by the static DependencyInjection class where it is invoked by "user code". The usage of ContainerBuilder and ownership of the container needs to be moved away from DependencyInjection.
2. Required: To satisfy (1), container configuration in user code must use a provided ContainerBuilder parameter rather than a call to the DependencyInjection class
3. Desirable: Remove coupling between user config code and DependencyInjection by forcing usage of Autofac modules. This would work by DependencyInjectionConfigAttribute pointing to an Autofac module class. This would be a very clean way to support (2) above

Changes:
- DependencyInjectionStartup will provide services down to InjectExtensionConfigProvider
- InjectExtensionConfigProvider will provide services down to InjectBindingProvider
- InjectBindingProvider will take ownership of Container instances and will 
  - create ContainerBuilder and populate with OOTB services
  - resolve DI config class and provide ContainerBuilder to it
  - provide the built container to InjectAttribute to resolve instances directly
- Remove DependencyInjection class
- VerifyConfiguration would not be able to work anymore. I don't think this is a huge issue because simply running a function will identify any DI config issues.

Thoughts?

**Comment by roryprimrose** [comment]
I've got it working under netstandard - https://github.com/roryprimrose/azure-function-autofac-dependency-injection/commits/feature/PortServices

I have retained NET46 using compiler directives as I'm not sure if you want to move to NET461. I didn't look into the full framework examples as the configuration files are missing data and I haven't had a chance to look into it yet.

**Comment by roryprimrose** [comment]
Can you please review that branch and let me know what you want to do about the full framework version. I can then make some final updates and send a PR.

**Comment by rawrspace** [comment]
I had a look earlier today and overall it looked good. I'm fine with updating to 4.6.1. once you finish your changes do a PR and I'll check it out.

Thanks!

**Comment by tdwright** [comment]
Hi @vandersmissenc,

Would an alternative be write a new attribute that could be used to mark a binding as a dependency to be registered? That way I could use a binding as a dependency for a service I'm injecting.

Could look something like this:

```
[FunctionName(AzureFunctionName)]
public static async Task Run(
	[QueueTrigger(QueueName, Connection = "AzureWebJobsStorage")]Message message,
	[CosmosDB(...params...), RegisterDependency] DocumentClient cosmosDBClient,
	[Inject]IMessageCooldownsService messageCooldownsService)
{
	...
}
```

Reckon that'd work? If so, I'm happy to give it a go and raise a PR.

**Comment by rawrspace** [comment]
@tdwright It may be possible to get this working but since you are adding a parameter to an existing attribute or making a new attribute that passes through to the non parameter version you may encounter some trouble. Rory and I had attempted in #26 to register all the dependencies from the Functions side container on startup and were running into problems. If you want to have a go at it I would be happy to accept a PR with this working.
