### ISSUE TITLE
Inject ILogger/TraceWriter to services

### ISSUE THREAD

**Issue by thiagospassos** [introtocomputerscience/azure-function-autofac-dependency-injection#27]
First of all, thanks for putting this pkg together, it's awesome. 

Now, this is more like a question than a feature request.

Have you found a way to inject the ILogger or TraceWriter into command/queries, so you don't need to log in the function itself?

```
[FunctionName(nameof(DoSomething))]
public static async Task DoSomething(
    [HttpTrigger(AuthorizationLevel.Function, "get", Route = null)]HttpRequest req,
    //use this inside the DoSomethingCommand 
    ILogger log,
    [Inject] IDoSomethingCommand cmd)
{
    await cmd.Execute();
}

public class DoSomethingCommand : IDoSomethingCommand
{
    private readonly ILogger _logger;
    public DoSomething(ILogger logger){
        _logger = logger;
    }
    public async Task Execute(){
        _logger.LogInformation("Something was executed");
    }
}

```

**Comment by roryprimrose** [comment]
I posted about this recently (https://www.neovolve.com/2018/04/05/dependency-injection-and-ilogger-in-azure-functions/). The LoggerModule can be applied to this extension library although you may need to make some adjustments depending on the version of Azure Functions you are running. Check the comments for a v2 workaround. Also, I'm not sure if Microsoft made changes to the logging filter so you will just need to test whether the Autofac module works as is in v2 (I haven't checked yet).

**Comment by thiagospassos** [comment]
Thanks, @roryprimrose, I'll give it a try and let you know how it goes.
