### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by AdrianPell** [introtocomputerscience/azure-function-autofac-dependency-injection#32]
**Is your feature request related to a problem? Please describe.**
Is there a reason why this project is licensed as GPL 3.0?  Autofac and other extensions are licensed as MIT.

**Describe the solution you'd like**
Change license to MIT

**Additional context**
If I understand it correctly, using a GPL 3.0 license means that anything built using this project would itself have to be licensed as GPL 3.0 in source form, etc.  For a commercial project (or even an internal-only project) that's probably a showstopper.  The MIT license, by contrast, is about as permissive as they get and would seem to be ideal here.

I have a PR related to per-function invocation resolution that I'd like to send you at some point.

**Comment by rawrspace** [comment]
Done
