### ISSUE TITLE
Resolve method errors out

### ISSUE THREAD

**Issue by epitka** [introtocomputerscience/azure-function-autofac-dependency-injection#35]
**Describe the bug**
Trying to write test to ensure that all dependencies are registered, and to make sure I don't have false positive, I left out registration of some types needed to construct type I am testing. VerifyConfiguration still passes. So I looked at "Resolve" and when I use that it fails with a message that I did not register component I am trying to resolve.

Here is my test: 
```
[Theory]
[InlineData(typeof(PaymentToMerchantProcessor))]
 public void can_wire_up_type(Type t)
 {
        var config = new DIConfig("ProcessPaymentToMerchantCompletedEvent");

        DependencyInjection.VerifyConfiguration(t);

        DependencyInjection.Resolve(t, "name", "ProcessPaymentToMerchantCompletedEvent", Guid.NewGuid());
}
```

**Comment by rawrspace** [comment]
Thanks for reporting the bug. I will check it out ~early next week~ as soon as I can.

**Comment by rawrspace** [comment]
Somehow I overlooked this issue. I don't expect you are still dependent on this but if you are can you provide a repro project so that I can investigate this further?
