### ISSUE TITLE
Configuration Settings not picked up from appsettings.json file

### ISSUE THREAD

**Issue by subhendu-de** [introtocomputerscience/azure-function-autofac-dependency-injection#37]
**Describe the bug**
We are using DI and IConfiguration to load the configuration settings from the config file. Apparently the local debugging reads the content from the appsettings.json file but when we deploy the Azure Function, it doesn't read the settings from the appsettings.json. We had to define all the setiings as Application Setting to make it work.

**To Reproduce**
```
    public class DIConfig
    {
        public DIConfig(string functionName)
        {
            DependencyInjection.Initialize(
                builder =>
            {
                builder.RegisterModule(new RegisterModule());
            },
                functionName);
        }
    }
```

```
    public class RegisterModule : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterType<Repository>().As<IRepository>();
            builder.RegisterType<IBusiness>().As<IBusiness>();
            builder.RegisterInstance(ConfigManager()).As<IConfiguration>().SingleInstance();
        }

        private static IConfigurationRoot ConfigManager()
        {
            return new ConfigurationBuilder()
                               .SetBasePath(Directory.GetCurrentDirectory())
                               .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                               .AddEnvironmentVariables()
                               .Build();
        }
    }
```

```
   [DependencyInjectionConfig(typeof(DIConfig))]
    public static class TestFunction
    {
        [FunctionName("TestFunction")]
        public static async Task<IActionResult> GetDetailsAsync([HttpTrigger(AuthorizationLevel.Function, "get", Route = "values/{id}")]HttpRequestMessage req, string id, [Inject]IBusiness business)
        {
            // code
        }
     }
```

**Expected behavior**
It should read the data from the configuration file. Any help is really appreciated.

**Comment by rawrspace** [comment]
Are you using Azure Functions v1 or v2? Also can you check out step 5 on this page and see if updating your ConfigManager to match helps? https://blog.jongallant.com/2018/01/azure-function-config/

**Comment by ranouf** [comment]
Hi,

My service needs to get an Implementation of IOptions<MyServiceSettings>. Using your code and your link, do you know how to inject it using Autofac?

thanks

**Comment by rawrspace** [comment]
@ranouf If IOptions is registered in the Azure Functions DI system then that question is related to #25 which we have not yet resolved. There was a PR #26 that aimed to do that but it wasn't fully able to work without error. I would eventually like to get that working but at the moment I don't have time to look into it. Hopefully Azure Functions provides native DI at some point in the future.
