### ISSUE TITLE
Configuration Dependency Injection

### ISSUE THREAD

**Issue by DownUnderDev** [introtocomputerscience/azure-function-autofac-dependency-injection#38]
```             
builder.Register(cfg =>
{
                    var config = new ConfigurationBuilder()
                        .SetBasePath(Directory.GetCurrentDirectory())
                        .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
                        .AddEnvironmentVariables()
                        .Build();
                    MySection asc = new MySection();
                    config.GetSection("MySection").Bind(asc);
                    return Options.Create(asc);
}).As<IOptions<MySection>>();
```
Trying to do something like this but dont have any access to ExecutionContext to get the current directory

Have you got any recommendations

**Comment by rawrspace** [comment]
A similar question just came up in #5 . Is there a reason that you can't do what part 3 of [this article](https://www.koskila.net/how-to-access-azure-function-apps-settings-from-c/) says? 

Essentially your settings get put as app settings and you access them with the method described in the article.

I'll see if I can find some time to see if the context can be passed in. My initial thought is that when registration runs we don't yet have the context object. I'll update with my findings.

**Comment by DownUnderDev** [comment]
I'm using a shared library that has required services in it that use the IOptions pattern, I may have to just break the convention here and not force it.  :(

**Comment by lxalln** [comment]
I managed to get this working in a hacked version of the library, we have been running it in production on v2 functions for a few weeks now. I had to break support for net46, I wasn't sure how to support both.

I altered `InjectExtensionConfigProvider` to take an `IOptions<ExecutionContextOptions>` as a dependency. This class has the AppDirectory. I got the information from [this issue](https://github.com/Azure/azure-webjobs-sdk/issues/1817#issuecomment-418430676).

I then passed this down through into `InjectBindingProvider` and changed the signature of the DependencyInjection class from `InjectionConfig(string functionName)` to `InjectionConfig(string functionName, string basePath)`.

That means I get the current path the function is running in when setting up my configuration:

```csharp
var configBuilder = new ConfigurationBuilder()
                    .SetBasePath(basePath)
                    .AddJsonFile("settings.json");
```

I'm happy to put this together as a pull request, but I believe `IOptions` is not available for net46, so a decision will need to be made about that.

Updated `InjectionExtensionConfigProvider`:
```csharp
public class InjectExtensionConfigProvider : IExtensionConfigProvider
{
    private readonly InjectBindingProvider bindingProvider;

    public InjectExtensionConfigProvider(IOptions<ExecutionContextOptions> options)
    {
        var appDirectory = options.Value.AppDirectory;
        this.bindingProvider = new InjectBindingProvider(appDirectory);
    }

    public void Initialize(ExtensionConfigContext context)
    {
        context.AddBindingRule<InjectAttribute>().Bind(this.bindingProvider);
    }
}
```

**Comment by rawrspace** [comment]
That's great @lxalln ! You may be able to use an [#if directive](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if) to only include the code in netstandard. That way we could add support for it while not breaking net46 support. I am happy to accept PRs if you are interested in working on it.
