### ISSUE TITLE
IOptions DI in Azure Function

### ISSUE THREAD

**Issue by ranouf** [introtocomputerscience/azure-function-autofac-dependency-injection#40]
Hi, 

I would like to resolve IOptions<MySettings> using _AzureFunctions.Autofac_ nuget package.

Usually in a webapi, we can use:

        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            [...]

            services.Configure<MySettings>(config.GetSection("My"));

            // Autofac
            var builder = new ContainerBuilder();
            builder.Populate(services);

            [...]
        }

But in an Azure function, the populate option is not available throw the nuget package `Autofac.Extensions.DependencyInjection`:
![image](https://user-images.githubusercontent.com/1764519/58432724-d5f12d00-8081-11e9-8486-60b80e40ba1b.png)

How are you available to access to IOptions<MySettings> in Azure function using Autofac DI?

Thanks for your help.

Source: https://github.com/autofac/Autofac/issues/991

**Comment by ranouf** [comment]
Solution: Install the version 4.3.0 of Autofac.Extensions.DependencyInjection nuget package.

**Comment by ranouf** [comment]
Do you plan to update the dependancies?

**Comment by rawrspace** [comment]
Azure functions requires version 4.2.1. More information is available in #7 . Until they remove this requirement I cannot update the dependency.
