### ISSUE TITLE
IHttpClientFactory injection problem

### ISSUE THREAD

**Issue by black-byte** [introtocomputerscience/azure-function-autofac-dependency-injection#43]
**Describe the bug**
Hello, i have service that uses IHttpClientFactory, and i can't resolve that IHttpClientFactory

I've tried also using docs https://docs.microsoft.com/bs-cyrl-ba/azure/azure-functions/functions-dotnet-dependency-injection 
which helps me to inject as described IHttpClientFactory using constructor. But still i can't figure out how i can inject  IHttpClientFactory so i will be able to use [Inject] attribute ? 

Any advices on that issue ?

**Comment by rawrspace** [comment]
This repository is for AzureFunctions.Autofac and not for native dependency injection. Can you verify that you are using this repositories package? 

If you are using this repos package then please provide a reproduction project and I can assist.

**Comment by black-byte** [comment]
I'm using  the correct package for DI (AzureFunctions.Autofac).
My problem is that i have no idea how i can register IHttpClientFactory using AzureFunctions.AutoFac.

In normal WebApi application i've to invoke method AddHttpClient on services (IServiceCollection) in my Startup.cs  then i'm invoking on ContainerBuilder Populate method with passing that IServiceCollection reference.

But here there is no straight way to invoke Populate method with passing IServiceCollection which contains registration of HttpClient (IHttpClientFactory)

Is there any workaround for that issue so i can use only AzureFunctions.Autofac as my DI container ? 

I will provide a reproduction project of that issue today and update it.

**Comment by rawrspace** [comment]
Based on what I am reading [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) in the documentation. You would typically in the Startup.cs do something like: `services.AddHttpClient<IMyService, MyService>();` . If that is the case then what prevents you from simply registering the service with Autofac and injecting it? If you require multiple implementations of the same interface you can use [named dependencies](https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection#using-named-dependencies) which I cover in the documentation.

As to the question of using the IServiceCollection; this has come up before and we attempted to implement the functionality but were unable to at that time. See the relevant issue #25 and PR #26 . 

If you must have an IHttpClientFactory then perhaps you can leverage the native DI to inject it and utilize AzureFunctions.Autofac for more complex things such as named dependencies.

**Comment by magoicochea** [comment]
If you are using AzureFuncitons.Autofac you can do the following on your Autofac configuration class.

```
//Microsoft DI Integration
var services = new ServiceCollection();
services.AddHttpClient("Client1");
services.AddHttpClient("Client2");
builder.Populate(services);
```

Where builder is the autofac builder reference that you get on the DependencyInjeciton.Initialize function.

To use the Populate extension you will need to install the package Autofac.Extensions.DependencyInjection. You need to install version 4.2.2 because AzureFunctions.Autofac has a dependency on version 4.2.1 of Autofac.

**Comment by rebeccapowell** [comment]
FYI: The implementation of IHttpClientFactory (DefaultHttpClientFactory) is tightly tied to the DI implementation in the Microsoft.Extensions.DependencyInjection NuGet package. For more information about using other DI containers, see [this](https://github.com/dotnet/extensions/issues/1345) GitHub discussion.

Source: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

AutoFac will inject the HttpClient, but it will be a new instance very time, defeating the purpose of the AddHttpClient() extension.

If you want to do this properly, I think you'd need to take this approach: https://stackoverflow.com/questions/58791239/how-to-register-typed-httpclient-service-with-autofac

Note, that SO answer is a bit old, and you'd need to use the ResolveMiddleware in Autofac now instead: https://autofaccn.readthedocs.io/en/latest/examples/log4net.html

What you are really aiming for is this:

```
services.AddHttpClient("MyHttpClient", client =>
            {
                client.DefaultRequestHeaders.Add("Instance", Guid.NewGuid().ToString());
            });
```

```
builder.Register(c => c.Resolve<IHttpClientFactory>().CreateClient("MyHttpClient"))
                .As<HttpClient>();
```

And then:

```
public class MyHttpClient : IMyHttpClient
{
	private HttpClient _httpClient;

	public MyHttpClient(HttpClient httpClient)
	{
		_httpClient = httpClient;
	}

	/// .......

	private async Task<T> EnvokeService<T>()
	{
		var instance = _httpClient
			.DefaultRequestHeaders
			.FirstOrDefault(x =>
				x.Key.Equals("instance", StringComparison.InvariantCultureIgnoreCase))
			.Value.FirstOrDefault();
		Console.WriteLine($"Instance: {instance}");

		var responseMessage = await _httpClient.SendAsync(_httpRequestMessage, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);
		responseContent = await responseMessage.Content.ReadAsStringAsync();

		if (responseMessage.IsSuccessStatusCode)
		//.........
	}
}
```

If that Guid output isn't consistent, then you're getting a new instance....

**Comment by kikaragyozov** [comment]
@rebeccapowell It's weird, because if you just create a named instance, and the autofac type you've registered via `builder.RegisterType`, when the constructor of that type accepts a `IHttpClientFactory`, it successfully resolves calls to all the registered named instances, meaning that it somehow resolved the DI for `IHttpClientFactory`?

How is that possible? And if it is possible for `IHttpClientFactory`, without any special handling, why can't it resolve a `HttpClient` being created by that `IHttpClientFactory`?
