### ISSUE TITLE
Allow newer versions of Autofac to be used

### ISSUE THREAD

**Issue by magoicochea** [introtocomputerscience/azure-function-autofac-dependency-injection#44]
At the moment I need to use Autofac.Extensions.DependencyInjection on my project in order to be able to use builder.Populate() and add services from the Microsoft Dependency Injection Framework like .AddHttpClient().

However, the latest release needs Autofac to be upgraded to 4.9.1. The project has a dependency on Autofac 4.2.1, which is making me have to use an older version of this nuget package (version 4.2.2).

Is there any reason why the dependency is Autofac=4.2.1 and not Autofac>=4.2.1? Version 4.2.1 was released almost three years ago.

**Comment by rawrspace** [comment]
Autofac 4.2.1 is required due to a hard internal dependency by the Azure Functions team. This came up before in issue #15 and was resolved by fixing the version in #17. Unfortunately at this time the version of autofac cannot be upgraded.

**Comment by magoicochea** [comment]
I see that the version of Autofac has now been updated to 4.6.2 on the main branch. Are the issues mentioned before no longer valid or should I be aware of them when upgrading the library?

**Comment by rawrspace** [comment]
They updated the internal package in Azure Functions to 4.6.2 and this package began throwing errors. The version of Autofac was identified as the issue and fixed in #47 . We are still locked to this version though, we can't just use any version.
