### ISSUE TITLE
Upgrade to Core 3.1

### ISSUE THREAD

**Issue by evilChipmunk** [introtocomputerscience/azure-function-autofac-dependency-injection#49]
We've been using the package successfully with Azure functions running on 2.2 Core, but have recently began upgrading to 3.0 (and then eventually 3.1). This package kept us from upgrading successfully - but it is integral to our process. 

Do you have plans on upgrading this to Core 3.0 + ?

**Comment by rawrspace** [comment]
What are the issues that you are seeing? Is it just that it says there is no version built for 3.0?

If you can tell me the steps to replicate the issue on a new project (might be simple), or provide a sample project I can see about how difficult it would be to port it to 3.0

**Comment by rawrspace** [comment]
@evilChipmunk please see #48  where @GuillaumeGuerra was able to sucessfully use .net core 3.1 with this package. Please confirm your settings and dependencies match his outlined in the response.
