### ISSUE TITLE
How to register or add the ExecutionContext to container?

### ISSUE THREAD

**Issue by michaelsync** [introtocomputerscience/azure-function-autofac-dependency-injection#5]
Is there any way to add the ExecutionContext to the container so I can access it outside of "Run" method?

**Comment by rawrspace** [comment]
Unfortunately at this time that is not an option. In functions v2 they have talked about adding DI natively which will likely then support it. For now you need to inject your resources into the run method and pass them to the methods or classes as needed. If you can share a code sample of what you are trying to accomplish I might be able to give you some advice on doing it a different way.

**Comment by tzkhan** [comment]
I'm trying to register a custom service in my DI config and need to pass in configuration values in to the service's ctor, like so:

```
builder.Register(c => new ClientService("<read from configuration>")).As<IClientService>();
```

How do I achieve this? One approach would be to build up the configuration via `ConfigurationBuilder` but then I'd need access to the `ExecutionContext` to the set the base path of the configuration json file.

Any advice?

**Comment by rawrspace** [comment]
Are you using functions v1 or v2? In functions v1 you can use ConfigurationManager.AppSettings["Setting"] to get the value. When running locally this is the value from local.setings.json and when running deployed it is the value in your app settings tab in the portal. 

Part 3 of this guys article, https://www.koskila.net/how-to-access-azure-function-apps-settings-from-c/ , lays out a method that should work for either version.

**Comment by tzkhan** [comment]
Thanks @vandersmissenc!

I'm using v2 and I've ended up using the Environment variables approach `Environment.GetEnvironmentVariable`
