### ISSUE TITLE
RegisterAssemlyTypes now working for ClosedTypes

### ISSUE THREAD

**Issue by hrsiddareddy** [introtocomputerscience/azure-function-autofac-dependency-injection#51]
Hi

We are using the same register code lines for our WebApi and Azure Function V2.
But the below dependency is not getting resolved in Azure function instance where as seems to be working fine in WebApi
AutoFac - 4.6.2

//For Core
var assemblies = Assembly
                                .GetEntryAssembly()
                                .GetReferencedAssemblies().Select(a=> Assembly.Load(a.Name)).ToArray();

//For Framework
var assemblies = System.Web.Compilation.BuildManager.GetReferencedAssemblies().Cast<Assembly>().ToArray();

builder.RegisterAssemblyTypes(assemblies)
                .AsClosedTypesOf(typeof(IContainerRetriever<,>))
                .AsImplementedInterfaces();

//Abstract Class
public abstract class BaseContainerRetriever<TContract, TContainerFilter, TEntity> : IContainerRetriever<TContainerFilter,TContract> where TContract : class where TContainerFilter: class 
    {
}
//Final Implemented class
public class AssetContainerRetriever : BaseContainerRetriever<Inventory, InventoryContainerFilter , InventoryData>
 {
}

IContainerRetriever<Inventory,InventoryData> is not getting resolved.

Please help me out here.

Regards
Hari

**Comment by rawrspace** [comment]
Can you please provide a sample project if you would like me to investigate?

**Comment by hrsiddareddy** [comment]
Hi 

I have created a sample project that is implemented in the same way. When "Function1" is in trigger mode you will notice that dependency injection is failing.
https://drive.google.com/open?id=1doEg52pXXRpM4lQ68YBYVWa7JxQ6meKT

Thanks for your response.

**Comment by rawrspace** [comment]
Sorry for the delays in responding. As you know things have gotten rather hectic across the globe and switching to remote work with the kids has been a bit difficult. 

The link you provided is for google drive. Would you please create a repository on github that contains the sample project?
