### ISSUE TITLE
RegisterLoggerFactory doesnt work

### ISSUE THREAD

**Issue by lucax88x** [introtocomputerscience/azure-function-autofac-dependency-injection#52]
**Describe the bug**
I'm using your new RegisterLoggerFactory extension in order to inject ILogger on my classes.

However, I can inject it but I cannot log anything in my classes.

keep in mind that:

- if I inject the ILogger in functions, they logs
- if I try to create my custom ILoggerFactory in the IOCconfig instead of using the 2nd parameter (the one after functionName) then it works

What I'm doing wrong?

**To Reproduce**
1. Inject RegisterLoggerFactory
2. Inject ILogger<T> somewhere
3. Log something

**Expected behavior**
I should see logs in my console

**Comment by bradtglass** [comment]
@lucax88x I had a similar issue I think, see PR #53 that I've just added. In my case I just needed to update the logging configuration in host.json
