### ISSUE TITLE
Dependency resolution graph for injected services

### ISSUE THREAD

**Issue by prabh-62** [introtocomputerscience/azure-function-autofac-dependency-injection#56]
**Is your feature request related to a problem? Please describe.**
To better understand and debug issues related to Dependency Injection, and also, it becomes easier to investigate when one understands the dependency resolution graph

**Describe the solution you'd like**
Autofac v6 release provides the [ability to create resolution graph of injected services](https://autofaccn.readthedocs.io/en/latest/advanced/debugging.html#dot-graph-tracer). Provide the ability to hook into container and subscribe to diagnostic events
![DotComplexTrace](https://user-images.githubusercontent.com/13006107/95618000-511a6f80-0a3a-11eb-8b1f-d0af0a997af2.png)

**Describe alternatives you've considered**

**Additional context**
Nuget: [Autofac.Diagnostics.DotGraph ](https://www.nuget.org/packages/Autofac.Diagnostics.DotGraph/)

**Comment by rawrspace** [comment]
I'll think about adding this as an add-on package because it only is available for Autofac 6 and adding it would force the version for this package.

**Comment by rawrspace** [comment]
@prabh-62 Could you check out https://www.nuget.org/packages/AzureFunctions.Autofac/4.0.1-alpha and provide feedback on if this meets your needs?

I added the ability to put post container actions. More info is [here](https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/tree/function/dot-graph-support#post-build-container-setup) and you can see an example using it [here](https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/blob/function/dot-graph-support/DOTGraphTracerExample/Configs/DIConfig.cs)

After running that example I produced a .dot file with the contents:
```
digraph G {
label=<DOTGraphTracerExample.Interfaces.IGreeter<br/><font point-size="8">Operation #1</font>>;
labelloc=t
n3634cf42658a430c88ab0f72bc73cfcd [shape=component,label=<
<table border='0' cellborder='0' cellspacing='0'>
<tr><td port='n6d4a29d4a51e446f8d8c0e9a4e8af8cb'>DOTGraphTracerExample.Interfaces.IGreeter</td></tr>
<tr><td><font point-size="10">Component: DOTGraphTracerExample.Models.Greeter</font></td></tr>
<tr><td><font point-size="10">Instance: DOTGraphTracerExample.Models.Greeter</font></td></tr>
</table>
>];
}
```
And I was able to convert it to the image:

![4c30da60-c7d2-4e36-a391-05efd370633a dot](https://user-images.githubusercontent.com/5750739/96007680-585bc780-0e04-11eb-8044-390fbee0e3e7.png)

If this all seems good I can go ahead and release it. If there is any feedback let me know.
