### ISSUE TITLE
Instances are resolved from the container, instead of from a lifetime scope

### ISSUE THREAD

**Issue by tsahi** [introtocomputerscience/azure-function-autofac-dependency-injection#6]
Your code resolves instances like this:
https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/blob/d0f3054e13ae2103501f245ed3214e00fd504a4f/AzureFunctions.Autofac/Configuration/DependencyInjection.cs#L29
where `container` is the `IContainer` interface. However, the Autofac documentation has this to say about resolving instances from the container:

> **While it is possible to resolve components right from the root container, doing this through your application in some cases may result in a memory leak.** It is recommended you always resolve components from a lifetime scope where possible to make sure service instances are properly disposed and garbage collected.

[Resolving Services](http://autofac.readthedocs.io/en/latest/resolve/index.html#resolving-services)

So you should resolve the instances from whatever lifetime scope which is appropriate for a function, and not directly from the container.

**Comment by rawrspace** [comment]
While that is true, the lifetime of a function is short-lived so garbage collection will clean it up fairly quickly and should not result in a severe memory leak. If you would like to take a stab at changing it to use lifetime scopes I am more than happy to approve pull requests.
