### ISSUE TITLE
ILifetimeScope not disposed on V1 functions

### ISSUE THREAD

**Issue by supereddie** [introtocomputerscience/azure-function-autofac-dependency-injection#60]
**Describe the bug**
After following the documentation for adding DI to a V1 function app, the `ILifetimeScope` objects are not disposed after a function has finished executing causing memory 'leaks'. A function app actually crashed for running out of memory.

**To Reproduce**
1. Make a simple DI config that writes something OnRelease:
```csharp
public class DependencyInjectionSetup
{
  public DependencyInjectionSetup(string functionName)
  {
    DependencyInjection.Initialize(builder =>
    {
      builder.RegisterType<SomeClass>().As<SomeInterface>().OnRelease(c => System.Diagnostics.Trace.WriteLine("Releasing SomeInterface"));
    }
  }
}
```
2. Add `[DependencyInjectionConfig(typeof(DependencyInjectionSetup))]` to the function static class
3. `[Inject]` the `SomeInterface` as a parameter in the function
```csharp
[FunctionName(nameof(TriggerTest))]
public static async Task TriggerTest(
  [TimerTrigger("0 */1 * * * *")] TimerInfo timer, 
  TraceWriter log,
  [Inject] SomeInterface someInterfaceInstance)
{
  ///
}
```
4. After the function has run, notice that there is no message in the debug output, indicating that the `ILifetimeScope` was not disposed.

**Expected behavior**
An message in the debug output 'Releasing SomeInterface'

**Additional context**
A crude fix that seems to work: Use the [FunctionInvocationFilterAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.host.functioninvocationfilterattribute?view=azure-dotnet) in a similar way the `ScopeFilter` is used:
```csharp
public sealed class ScopeFilterAttribute : FunctionInvocationFilterAttribute
{
  public override Task OnExecutedAsync(FunctionExecutedContext executedContext, CancellationToken cancellationToken)
  {
    RemoveScope(executedContext.FunctionInstanceId);
    return Task.CompletedTask;
  }

  public override Task OnExecutingAsync(FunctionExecutingContext executingContext, CancellationToken cancellationToken)
  {
    return Task.CompletedTask;
  }

  private static void RemoveScope(Guid functionInstanceId)
  {
    DependencyInjection.RemoveScope(functionInstanceId);
  }
}
```
Then apply this attribute to the Function class, similar to `DependencyInjectionConfig`. Now the 'Releasing SomeInterface' will appear in the debug output after the function has executed.

This may not be correct approach, but for now it seems to work here.

**Comment by rawrspace** [comment]
As you have done some research into the issue would you be interested in implementing the fix and submitting a pull request?

**Comment by rawrspace** [comment]
@supereddie Thanks for contributing. The package will be published shortly here: https://www.nuget.org/packages/AzureFunctions.Autofac/4.0.2

I rolled it in with some other changes I had pending.

**Comment by supereddie** [comment]
@rawrspace glad I could help. I don't know how many users are still using Functions V1, but it should be OK to add one extra attribute for those that do. 

I was thinking of perhaps letting `DependencyInjectionConfig` inherit from `FunctionInvocationFilterAttribute` instead, but that would require extra compiler directives, is not really backwards compatible and make the `DependencyInjectionConfig` do a new and different thing. An extra attribute seemed safer for existing code.

**Comment by rawrspace** [comment]
I agree with the extra attribute. I don't have statistics on it but I am sure very few users are still using this with Functions V1 and the way you implemented the fix allows them to opt in or opt out as they want.

**Comment by supereddie** [comment]
Yes, I am in favour for opting in or out on things like this. Especially for old V1 functions that should really be migrated to V3...
