### ISSUE TITLE
Error with Autofac 4.7

### ISSUE THREAD

**Issue by s-KaiNet** [introtocomputerscience/azure-function-autofac-dependency-injection#7]
Yesterday autofac 4.7 was released, however, your module tries to find autofac 4.6.2. As a result an error `Could not load file or assembly 'Autofac, Version=4.6.2.0` is thrown. 
I believe you should add an explicit dependency on autofac in .nuspec file.

**Comment by rawrspace** [comment]
Can you provide the steps needed to reproduce this issue? Right now the AzureFunctions.Autofac package has a dependency on Autofac >= 4.6.2. I was able to create a new azure function project, update to AzureFunctions.Autofac v2.1.0 then update Autofac to 4.7 and it still built and ran without issue.

**Comment by s-KaiNet** [comment]
that's right... I missed that, there is a dependency on autofac. Looks like an issue with dependencies in VS2017....  `AzureFunctions.Autofac` installs autofac automatically, however as soon as you go to "Manage nuget packages" and add autofac explicitly, it stops working for me.

**Comment by rawrspace** [comment]
Can you share a sample repro project? I was able to install AzureFunctions.Autofac 2.1.0 and then update to Autofac 4.7.0 without issue.

**Comment by s-KaiNet** [comment]
You can try this [one](https://github.com/s-KaiNet/azfunc-repro).   
For me steps are below:  
1. Clone the repo & open project in VS2107 
2. F5 -> error in console (cli 1.0.1.0, functions sdk 1.0.13)

**Comment by Mytza** [comment]
Hi, I have the same issue, I tried updating autofac after installing to 4.8.1 but i receive the same error at runtime, build works fine without problems.

**Comment by Nazgaul** [comment]
I think its because the simulator is also using autofac and its using v 4.6.1. for me the solution was to downgrade autofac to 4.6.1 and everything worked

**Comment by rawrspace** [comment]
I converted the package over to .NET Standard and upgraded to the latest version of Autofac. Please let me know if you see issues in the new version. https://www.nuget.org/packages/AzureFunctions.Autofac/

**Comment by LeastOne** [comment]
@Nazgaul, @vandersmissenc, I ran into the same Autofac problem on https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/issues/3. The following two issues seem to indicate that the Azure Function Host has some dependencies on Autofac v4.2.1:

- https://github.com/Azure/azure-functions-host/issues/2979
- https://github.com/Azure/azure-functions-host/issues/1665

To deal with the problem I created this pull request, https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/pull/12, to simply downgrade to Autofac v4.2.1 which solved the runtime issue I was encountering. Given that most people will want to debug their functions using the Autofac Function Host (myself included) I think it would be ideal to downgrade for the time being. @vandersmissenc, would you be in favor of incorporating this downgrade?
